# Generated by Django 4.1.7 on 2023-02-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(default="", max_length=255)),
                ("text", models.TextField(default="")),
            ],
            options={
                "ordering": ("user",),
            },
        ),
    ]
