# Generated by Django 4.1.7 on 2023-02-23 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("message", "0002_message_chat_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="email",
            field=models.EmailField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="message",
            name="home_page",
            field=models.URLField(max_length=555, null=True),
        ),
    ]
