# Generated by Django 4.1.7 on 2023-02-23 15:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("message", "0003_message_email_message_home_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2023, 2, 23, 15, 28, 10, 320978, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
